# 使用 Ubuntu 最新的 LTS 版本作为基础镜像
FROM ubuntu:latest

# 设置标签
LABEL key="1.0"

# 设置非交互式安装模式，避免在构建过程中出现提示
ENV DEBIAN_FRONTEND=noninteractive

# 设置时区环境变量
ENV TZ=Asia/Shanghai 

# 安装 tzdata 包并设置时区
RUN apt-get update && apt-get install -y tzdata && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    dpkg-reconfigure --frontend noninteractive tzdata

# 设置中科大镜像为 Ubuntu 源
RUN sed -i.bak -e 's|http://archive.ubuntu.com/ubuntu/|https://mirrors.ustc.edu.cn/ubuntu/|g' \
               -e 's|http://security.ubuntu.com/ubuntu|https://mirrors.ustc.edu.cn/ubuntu|g' \
               /etc/apt/sources.list

# 安装软件包
RUN apt-get update && apt-get install -y \
    openssh-server \
    net-tools \
    git \
    unzip \
    ninja-build \
    neovim \
    ruby-full \
    cmake \
    nodejs \
    iputils-ping \
    procps \
    htop \
    traceroute \
    tree \
    coreutils \
    zsh \
    fontconfig \
    python3 \
    iproute2 \
    kitty \
    wget \
    pkg-config \
    graphviz \
    kotlin \
    golang \
    zip \
    software-properties-common \
    valgrind

# 清理缓存
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
